package com.mycompany.floriculturapi.views;

import com.mycompany.floriculturapi.dao.RelatorioAnaliticoDAO;
import com.mycompany.floriculturapi.dao.RelatorioSinteticoDAO;
import com.mycompany.floriculturapi.models.RelatorioAnalitico;
import com.mycompany.floriculturapi.models.RelatorioSintetico;
import com.mycompany.floriculturapi.utils.Validador;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Pedro
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelatoriosAnaliticos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelatoriosSinteticos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnDetalhes = new javax.swing.JButton();
        jdcDataInicio = new com.toedter.calendar.JDateChooser();
        jdcDataTermino = new com.toedter.calendar.JDateChooser();
        lblValorTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuMenu = new javax.swing.JMenuItem();
        mnuManutencaoCliente = new javax.swing.JMenuItem();
        mnuManutencaoProduto = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Data Inicio:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        tblRelatoriosAnaliticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Tipo", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRelatoriosAnaliticos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 170));

        tblRelatoriosSinteticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Cliente", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRelatoriosSinteticos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, 160));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Valor Total:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Data Término:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 30));

        btnDetalhes.setText("Detalhes");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });
        jPanel2.add(btnDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 180, 40));

        jdcDataInicio.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jdcDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jdcDataTermino.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jdcDataTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel2.add(lblValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 710, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jMenu1.setText("Abrir");

        mnuMenu.setText("Menu");
        mnuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuActionPerformed(evt);
            }
        });
        jMenu1.add(mnuMenu);

        mnuManutencaoCliente.setText("Manutenção de Cliente");
        mnuManutencaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManutencaoClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuManutencaoCliente);

        mnuManutencaoProduto.setText("Manutenção de Produto");
        mnuManutencaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManutencaoProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuManutencaoProduto);

        mnuVendas.setText("Vendas");
        mnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVendas);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendasActionPerformed
        Vendas vendas = new Vendas();
        this.dispose();
        vendas.setVisible(true);
    }//GEN-LAST:event_mnuVendasActionPerformed

    private void mnuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuActionPerformed
        Inicio inicio = new Inicio();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_mnuMenuActionPerformed

    private void mnuManutencaoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManutencaoClienteActionPerformed
        ManutencaoCliente manutencaoCliente = new ManutencaoCliente();
        this.dispose();
        manutencaoCliente.setVisible(true);
    }//GEN-LAST:event_mnuManutencaoClienteActionPerformed

    private void mnuManutencaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManutencaoProdutoActionPerformed
        ProdutoManutencao produtoManutencao = new ProdutoManutencao();
        this.dispose();
        produtoManutencao.setVisible(true);
    }//GEN-LAST:event_mnuManutencaoProdutoActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        Validador objValidador = new Validador();
        objValidador.validarData(jdcDataInicio);
        objValidador.validarData(jdcDataTermino);
        
        if(objValidador.hasErro()){
            JOptionPane.showMessageDialog(rootPane, objValidador.getMensagensErro());    
        }
        else{
            Date dataInicio = jdcDataInicio.getDate();
            Date dataTermino = jdcDataTermino.getDate();
            
            ArrayList<RelatorioSintetico> lista = RelatorioSinteticoDAO.listarPorPeriodo(dataInicio, dataTermino);
            
            DefaultTableModel modelo = (DefaultTableModel) tblRelatoriosSinteticos.getModel();
            modelo.setRowCount(0);
            for(RelatorioSintetico item : lista){
                modelo.addRow(new String[]{
                    String.valueOf(item.getIdVenda()),
                    String.valueOf(item.getDataVenda()),
                    item.getNomeCliente(),
                    String.valueOf(item.getValorVenda())
                });
            }
            
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        
        int linhaSelecionada = tblRelatoriosSinteticos.getSelectedRow();
        
        if(linhaSelecionada >= 0){
            DefaultTableModel modelo = (DefaultTableModel) tblRelatoriosSinteticos.getModel();
            lblValorTotal.setText(modelo.getValueAt(linhaSelecionada, 3).toString());
            int idVenda = Integer.parseInt(modelo.getValueAt(linhaSelecionada, 0).toString());
            
            ArrayList<RelatorioAnalitico> lista = RelatorioAnaliticoDAO.listarPorVenda(idVenda);
            DefaultTableModel modeloAnalitico = (DefaultTableModel) tblRelatoriosAnaliticos.getModel();
            modeloAnalitico.setRowCount(0);
            
            for(RelatorioAnalitico item : lista){
                
                modeloAnalitico.addRow(new String[]{
                    item.getNomeProduto(),
                    item.getTipoProduto(),
                    String.valueOf(item.getQtdProduto()),
                    String.valueOf(item.getValorUnitario())
                });
                
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha para exibir os detalhes");
        }
    }//GEN-LAST:event_btnDetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcDataInicio;
    private com.toedter.calendar.JDateChooser jdcDataTermino;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JMenuItem mnuManutencaoCliente;
    private javax.swing.JMenuItem mnuManutencaoProduto;
    private javax.swing.JMenuItem mnuMenu;
    private javax.swing.JMenuItem mnuVendas;
    private javax.swing.JTable tblRelatoriosAnaliticos;
    private javax.swing.JTable tblRelatoriosSinteticos;
    // End of variables declaration//GEN-END:variables
}
