package com.mycompany.floriculturapi.views;

import com.mycompany.floriculturapi.dao.ClienteDAO;
import com.mycompany.floriculturapi.models.Cliente;
import com.mycompany.floriculturapi.utils.Validador;
import java.awt.event.KeyEvent;
import static java.lang.Long.parseLong;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Pedro
 */
public class ManutencaoCliente extends javax.swing.JFrame {

    Cliente objAlterar = null;
    
    /**
     * Creates new form ManutencaoCliente
     */
    public ManutencaoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbDataNasc = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rbMasc = new javax.swing.JRadioButton();
        rbFem = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        lbSexo = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        lbEnd = new javax.swing.JLabel();
        dcDataNasc = new com.toedter.calendar.JDateChooser();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtConsulta = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuMenu = new javax.swing.JMenuItem();
        mnuVender = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbDataNasc.setText("Data de Nascimento:");
        jPanel2.add(lbDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        jPanel2.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, 25));

        lbNome.setText("Nome:");
        jPanel2.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbEmail.setText("Email:");
        jPanel2.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lbTel.setText("Telefone:");
        jPanel2.add(lbTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lbCpf.setText("CPF:");
        jPanel2.add(lbCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 260, 25));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 25));

        bgSexo.add(rbMasc);
        rbMasc.setText("Masc");
        jPanel2.add(rbMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        bgSexo.add(rbFem);
        rbFem.setText("Fem");
        jPanel2.add(rbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        bgSexo.add(rbOutro);
        rbOutro.setText("Outro");
        jPanel2.add(rbOutro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        lbSexo.setText("Sexo");
        jPanel2.add(lbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 25));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 260, 25));

        lbEnd.setText("Endereço:");
        jPanel2.add(lbEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        dcDataNasc.setDateFormatString("d '/' M '/' y");
        jPanel2.add(dcDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, 380));

        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 130, 60));

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 290, 60));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 290, 60));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Email", "Telefone", "CPF", "Endereço", "Sexo", "Data de Nasc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 630, 370));

        try {
            txtConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 260, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Digite o CPF para fazer uma pesquisa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("Abrir");

        mnuMenu.setText("Menu");
        mnuMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMenuActionPerformed(evt);
            }
        });
        jMenu1.add(mnuMenu);

        mnuVender.setText("Vender");
        mnuVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVenderActionPerformed(evt);
            }
        });
        jMenu1.add(mnuVender);

        mnuRelatorios.setText("Relatórios");
        mnuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRelatoriosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuRelatorios);

        mnuProdutos.setText("Manutenção de Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProdutos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        int linhaSelecionada = tblClientes.getSelectedRow();
        if(linhaSelecionada >= 0){
            
            DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();          
            int idExcluir = Integer.parseInt(modeloTabela.getValueAt(linhaSelecionada,0).toString());
            //chamar dao para excluir;
            boolean retorno = ClienteDAO.excluir(idExcluir);
            
            if(retorno){
                JOptionPane.showMessageDialog(rootPane, "Cliente deletado com sucesso!");
                atualizarTabela();
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Erro ao deletar cliente!");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    public void atualizarTabela(){
        ArrayList<Cliente> lista = ClienteDAO.listar();
        DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
        modeloTabela.setRowCount(0);
        
        for(Cliente item : lista){
            
            modeloTabela.addRow(new String[]{
                String.valueOf(item.getIdCliente()),
                item.getNomeCliente(),
                item.getEmailCliente(),
                item.getTelefoneCliente(),
                item.getCPF(),
                item.getEnderecoCliente(),
                item.getSexoCliente(),
                String.valueOf(item.getDataNasc())
                    
            });
        }
    }
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        //se tiver em alteração
        if(objAlterar != null){
            Validador objValidador = new Validador();
            objValidador.validarTexto(txtNome);
            objValidador.validarTexto(txtEmail);
            objValidador.validarTexto(txtEndereco);
            objValidador.validarBotao(bgSexo);
            objValidador.validarTexto(txtConsulta);
            objValidador.validarTexto(txtTelefone);
            objValidador.validarData(dcDataNasc);
            
            
            if(objValidador.hasErro()){
                   JOptionPane.showMessageDialog(rootPane, objValidador.getMensagensErro());
               }
            else{
                //resgatar dados
            String nome = txtNome.getText() ;
            String email = txtEmail.getText();
            String telefone = txtTelefone.getText();
            String sexo;
            String endereco = txtEndereco.getText();
            Date dataNasc = new java.sql.Date (dcDataNasc.getDate().getTime());
        
            if(rbMasc.isSelected())
                sexo = "Masculino";
            
            else if(rbFem.isSelected())        
                sexo = "Feminino";

            else
                sexo = "Outro";
            
            
            objAlterar.setDataNasc(dataNasc);
            objAlterar.setEmailCliente(email);
            objAlterar.setEnderecoCliente(endereco);
            objAlterar.setSexoCliente(sexo);
            objAlterar.setNomeCliente(nome);
            objAlterar.setTelefoneCliente(telefone);
            
            //incluir dao
            boolean retornoAlteracao = ClienteDAO.alterar(objAlterar);
            
            if(retornoAlteracao){
                JOptionPane.showMessageDialog(rootPane, "Dados Alterados com sucesso!");
                //limpar campos
                objAlterar = null;
                txtNome.setText("");
                txtCPF.setText("");
                txtEmail.setText("");
                txtTelefone.setText("");
                txtEndereco.setText("");
                rbMasc.setSelected(false);
                rbFem.setSelected(false);
                rbOutro.setSelected(false);
                atualizarTabela();
            }
            else
                JOptionPane.showMessageDialog(rootPane, "Falha ao alterar os dados!");
            }
            
        }
        
        //se tiver em inclusão
        else{
            Validador objValidador = new Validador();
            objValidador.validarTexto(txtNome);
            objValidador.validarTexto(txtEmail);
            objValidador.validarTexto(txtEndereco);
            objValidador.validarBotao(bgSexo);
            objValidador.validarTexto(txtConsulta);
            objValidador.validarTelefone(txtTelefone);
            objValidador.validarData(dcDataNasc);
            objValidador.validarCPF(txtCPF);
            if(objValidador.hasErro()){
                JOptionPane.showMessageDialog(rootPane, objValidador.getMensagensErro());    
            }

            else{
                objValidador.limparMensagens();

                String nome = txtNome.getText() ;
                String cpf = txtCPF.getText() ;
                String email = txtEmail.getText();
                String telefone = txtTelefone.getText();
                String sexo;
                String endereco = txtEndereco.getText();
                //Date dataNasc = dcDataNasc.getDate();
                Date dataNasc = new java.sql.Date (dcDataNasc.getDate().getTime());

                if(rbMasc.isSelected())
                    sexo = "Masculino";

                else if(rbFem.isSelected())
                    sexo = "Feminino";

                else
                    sexo = "Outro";

                //Object[] dados = {nome, email, cpf, telefone, endereco, sexo, dataNasc};

                //tabelaCliente.addRow(dados);

                Cliente objCadastrar = new Cliente(cpf, nome, email, telefone,endereco, dataNasc, sexo);

                boolean retornoBanco = ClienteDAO.salvar(objCadastrar);

                if(retornoBanco){
                    JOptionPane.showMessageDialog(rootPane, "Cliente cadastrado com sucesso!");
                    txtNome.setText("");
                    txtCPF.setText("");
                    txtEmail.setText("");
                    txtTelefone.setText("");
                    txtEndereco.setText("");
                    rbMasc.setSelected(false);
                    rbFem.setSelected(false);
                    rbOutro.setSelected(false);
                    atualizarTabela();
                }

                else
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar cliente");

            }

        }
      
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        DefaultTableModel modeloClientes = (DefaultTableModel) tblClientes.getModel();
        int linhaSelecionada = tblClientes.getSelectedRow();
        
        if(linhaSelecionada >= 0){
           
            //int resposta = JOptionPane.showConfirmDialog(rootPane, "Você realmente deseja editar os dados deste cliente?", "Editar cliente", 2);
           
            //if(resposta == 0){
               
               
               
               
               
               //else{
                   //objValidador.limparMensagens();
                   String sexo;
                   if(rbMasc.isSelected())
                        sexo = "Masculino";
            
                    else if(rbFem.isSelected())
                        sexo = "Feminino";
            
                    else
                        sexo = "Outro";
                   
                   int id = Integer.parseInt(modeloClientes.getValueAt(linhaSelecionada, 0).toString());
                   String nome = modeloClientes.getValueAt(linhaSelecionada, 1).toString();
                   String email = modeloClientes.getValueAt(linhaSelecionada, 2).toString();
                   String telefone = modeloClientes.getValueAt(linhaSelecionada, 3).toString();
                   String cpf = modeloClientes.getValueAt(linhaSelecionada, 4).toString();
                   String endereco = modeloClientes.getValueAt(linhaSelecionada, 5).toString();
                   String sexoEditar = modeloClientes.getValueAt(linhaSelecionada, 6).toString();
                   String dataNasc = modeloClientes.getValueAt(linhaSelecionada, 7).toString();
                   
                   dataNasc = dataNasc.replace("-", "");
                   Long dataTeste = Long.parseLong(dataNasc);
                   Date dataFinal = new java.sql.Date(dataTeste);
                   
                 
                   objAlterar = new Cliente(id, cpf, nome, email,telefone, endereco, dataFinal, sexoEditar);
                   
                   txtNome.setText(objAlterar.getNomeCliente());
                   txtCPF.setText(objAlterar.getCPF());
                   txtEmail.setText(objAlterar.getEmailCliente());
                   txtTelefone.setText(objAlterar.getTelefoneCliente());
                   txtEndereco.setText(objAlterar.getEnderecoCliente());
                   dcDataNasc.setDate(objAlterar.getDataNasc());
                   
                   if("Masculino".equals(sexoEditar)){
                       rbMasc.setSelected(true);
                   }
                   else if("Feminino".equals(sexoEditar)){
                       rbFem.setSelected(true);
                   }
                   else{
                       rbOutro.setSelected(true);
                   }
                   
                   
                   
                   
                   /*tbCliente.setValueAt(txtNome.getText(), tbCliente.getSelectedRow(), 0);
                   tbCliente.setValueAt(txtEmail.getText(), tbCliente.getSelectedRow(), 1);
                   tbCliente.setValueAt(txtTelefone.getText(), tbCliente.getSelectedRow(), 2);
                   tbCliente.setValueAt(txtConsulta.getText(), tbCliente.getSelectedRow(), 3);
                   tbCliente.setValueAt(txtEndereco.getText(), tbCliente.getSelectedRow(), 4);
                   tbCliente.setValueAt(sexo, tbCliente.getSelectedRow(), 5);*/
               //}
            //}
            
            //else{
              //  JOptionPane.showMessageDialog(null,"Operação Cancelada");
           //}
          
       }
       
       else{
            JOptionPane.showMessageDialog(null,"Selecione um cliente para editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void mnuVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVenderActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMenuActionPerformed
        Inicio inicio = new Inicio();
        this.dispose();
        inicio.setVisible(true);
    }//GEN-LAST:event_mnuMenuActionPerformed

    private void mnuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuRelatoriosActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        if("   .   .   -  ".equals(txtConsulta.getText())){
            ArrayList<Cliente> lista = ClienteDAO.listar();
            DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
            modeloTabela.setRowCount(0);

            for(Cliente item : lista){

                modeloTabela.addRow(new String[]{
                    String.valueOf(item.getIdCliente()),
                    item.getNomeCliente(),
                    item.getEmailCliente(),
                    item.getTelefoneCliente(),
                    item.getCPF(),
                    item.getEnderecoCliente(),
                    item.getSexoCliente(),
                    String.valueOf(item.getDataNasc())

                });
            }
        }
        
        else{
            String cpfConsulta = txtConsulta.getText();
            ArrayList<Cliente> lista = ClienteDAO.pesquisa(cpfConsulta);
            DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
            modeloTabela.setRowCount(0);

            for(Cliente item : lista){

                modeloTabela.addRow(new String[]{
                    String.valueOf(item.getIdCliente()),
                    item.getNomeCliente(),
                    item.getEmailCliente(),
                    item.getTelefoneCliente(),
                    item.getCPF(),
                    item.getEnderecoCliente(),
                    item.getSexoCliente(),
                    String.valueOf(item.getDataNasc())

                });
            }
            txtConsulta.setText("");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCPFKeyTyped(java.awt.event.KeyEvent evt) {                                
        char c = evt.getKeyChar();

        if(txtConsulta.getText().length()>=11){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Máximo de 11 "
                + "caracteres atingido!");
        }
        if ( ((c < '0') || (c > '9')) && (c !=KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Digite Apenas números");
        }
    }                               

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {                                       

    }                                      

    private void txtTelefoneKeyTyped(java.awt.event.KeyEvent evt) {                                     
        char c = evt.getKeyChar();

        if(txtTelefone.getText().length()>=11){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Máximo de 11 "
                + "caracteres atingido!");
        }
        if ( ((c < '0') || (c > '9')) && (c !=KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(this,"Digite Apenas números");

        }
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManutencaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManutencaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManutencaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManutencaoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManutencaoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private com.toedter.calendar.JDateChooser dcDataNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEnd;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTel;
    private javax.swing.JMenuItem mnuMenu;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenuItem mnuRelatorios;
    private javax.swing.JMenuItem mnuVender;
    private javax.swing.JRadioButton rbFem;
    private javax.swing.JRadioButton rbMasc;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JTable tblClientes;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtConsulta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
